index/urls.py
from django.urls import path
from . import views
app_name ='index'
urlpatterns=[
    path('',views.index_home,name='index_home'),
    path('trending',views.index_trend,name='trending'),
    path('subscription',views.index_sub,name='subscription'),
    path('library',views.index_library,name='library'),
    path('history',views.index_history,name='history'),
    


]

ytclone/index/urls.py
from django.urls import path
from . import views
app_name ='index'
urlpatterns=[
    path('',views.index_home,name='index_home'),
    path('trending',views.index_trend,name='trending'),
     path('subscription',views.index_sub,name='subscription')
]

ytclone/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('index.urls'))
]

index/models.py
from django.db import models

# Create your models here.

index/views.py
from django.shortcuts import render

# Create your views here.

def index_home(request):
    return render(request,'index/home.html')

def index_trend(request):
    return render(request,'index/trending.html')

def index_sub(request):
    return render(request,'index/subscription.html')
    
def index_history(request):
    return render(request,'index/history.html')

def index_library(request):
    return render(request,'index/library.html')

ytclone/index/views.py
from django.shortcuts import render

# Create your views here.

def index_home(request):
    return render(request,'index/home.html')

def index_trend(request):
    return render(request,'index/trending.html')

def index_sub(request):
    return render(request,'index/subscription.html')

index/templates/index/history.html
{% extends 'index/master.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% block content %}
<div class="videos">
    <h2>Today</h2>
    <div class="video_container1">
        <div class="video">
            <img src="{% static 'images/trend1.jpg' %}">
            <div class="videoinfo">
            <h3>Xmas tree decoration</h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
        </div>
        </div>
    <div class="video">
        <img src="{% static 'images/trend2.jpg' %}">
        <div class="videoinfo">
        <h3>Xmas special</h3>
        <a href="">Lets Try This</a>
        <span>104K views</span>
        </div>
    </div>
    <div class="video">
        <img src="{% static 'images/sub3.jpg' %}">
        <div class="videoinfo">
        <h3>fifa game chart</h3>
        <a href="">Lets celebrate</a>
        </div>
    </div>
    <!-- <div class="video">
        <img src="{% static 'images/trend2.jpg' %}">
        <div class="videoinfo">
        <h3>Xmas special</h3>
        <a href="">Lets Try This</a>
        <span>104K views</span>
        </div>
    </div> -->
</div>
    <h2>Yesterday</h2>
    <div class="video_container1">
    <!-- <div class="video">

    </div>
    <div class="video">

    </div>
    <div class="video">
    </div> -->
    <div class="video">
        <img src="{% static 'images/trend1.jpg' %}">
        <div class="videoinfo">
        <h3>Xmas tree decoration</h3>
        <a href="">Lets Try This</a>
        <span>10K views</span>
    </div>
    </div>
    <div class="video">
        <img src="{% static 'images/sub2.png' %}">
        <div class="videoinfo">
        <h3>fifa teams</h3>
        <span>104K views</span>
        </div>
    </div>
    </div>
    {% endblock%}

index/templates/index/home.html
{% extends 'index/master.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% block content %}
 <!-- <div class ="buttonbar">
    <div class="button">
        <button value="All"></button>
        <button value="All"></button>
        <button value="All"></button>
        <button value="All"></button>
    </div>
 -->

<div class="videos">
   

    <h1>Recommended</h1>
    <div class="video_container">
        <div class="video">
            <img src="{% static 'images/ytvideo1.jpg' %}">
            <div class="videoinfo">
            <h3> website using HTML</h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
        </div>
        </div>
        <div class="video">
            <img src="{% static 'images/ytvideo2.jpg' %}">
            <div class="videoinfo">
            <h3>HTML video tag</h3>
            <a href="">Lets Try This</a>
            <span>100K views</span>
            </div>
        </div>

            <div class="video">
                <img src="{% static 'images/trend1.jpg' %}">
                <div class="videoinfo">
                <h3>Xmas tree decoration</h3>
                <a href="">Lets Try This</a>
                <span>10K views</span>
            </div>
            </div>
        <div class="video">
            <img src="{% static 'images/ytvideo3.png' %}">
            <div class="videoinfo">
            <h3> website using CSS</h3>
            <a href="">Lets Try This</a>
            <span>104K views</span>
            </div>
        </div>
        <div class="video">
            <img src="{% static 'images/ytvideo1.jpg' %}">
            <div class="videoinfo">
            <h3>Website using HTML</h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
            </div>
        </div>
        <div class="video">
            <img src="{% static 'images/sub2.png' %}">
            <div class="videoinfo">
            <h3>fifa teams</h3>
            <span>104K views</span>
            </div>
        </div>
        <div class="video">
            <img src="{% static 'images/ytvideo3.png' %}">
            <div class="videoinfo">
            <h3>html video tag</h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
            </div>
        </div>
         <div class="video">
            <img src="{% static 'images/ytvideo2.jpg' %}">
            <div class="videoinfo">
            <h3> website using HTML</h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
            </div>
        </div> 
        <div class="video">
            <img src="{% static 'images/trend3.jpg' %}">
            <div class="videoinfo">
            <h3> Xmas Candy</h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
            </div>
        </div>
         <div class="video">
            <img src="{% static 'images/ytvideo3.png' %}">
            <div class="videoinfo">
            <h3> website using HTML </h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
            </div>
        </div> 
        <div class="video">
            <img src="{% static 'images/ytvideo2.jpg' %}">
            <div class="videoinfo">
            <h3> website using HTML</h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
            </div>
        </div>  
         <div class="video">
            <img src="{% static 'images/ytvideo3.png' %}">
            <div class="videoinfo">
            <h3>website using HTML</h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
            </div>
        </div> 
        <div class="video">
            <img src="{% static 'images/ytvideo2.jpg' %}">
            <div class="videoinfo">
            <h3> website using HTML</h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
            </div>
        </div>  



    </div>
</div>
{% endblock %}

index/templates/index/library.html
{% extends 'index/master.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% block content %}
<div class="videos">
    <h4>History</h4>
    
    <div class="video_container">
        <div class="video">
            <img src="{% static 'images/trend1.jpg' %}">
            <div class="videoinfo">
            <h3>Xmas tree decoration</h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
        </div>
        </div>
        <div class="video">
            <img src="{% static 'images/trend2.jpg' %}">
            <div class="videoinfo">
            <h3>Xmas special</h3>
            <a href="">Lets Try This</a>
            <span>104K views</span>
            </div>
        </div>
        <div class="video">
            <img src="{% static 'images/trend3.jpg' %}">
            <div class="videoinfo">
            <h3> Xmas Candy</h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
            </div>
        </div>
        <div class="video">
            <img src="{% static 'images/trend4.jpg' %}">
            <div class="videoinfo">
            <h3>Xmas tree decor</h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
            </div>
        </div>
    </div>
    <h4>Watch Later</h4>
    <div class="video_container">
        <div class="video">
            <img src="{% static 'images/trend1.jpg' %}">
            <div class="videoinfo">
            <h3>Xmas tree decoration</h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
        </div>
        </div>
        <div class="video">
            <img src="{% static 'images/sub4.jpg' %}">
            <div class="videoinfo">
            <h3>fifa group</h3>
            <a href="">lets enjoy</a>
            <span>10K views</span>
            </div>
        </div>
         <div class="video">
            <img src="{% static 'images/sub5.jpg' %}">
            <div class="videoinfo">
            <h3> fifa group chart</h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
            </div>
        </div> 
         <div class="video">
            <img src="{% static 'images/sub6.jpg' %}">
            <div class="videoinfo">
            <h3>fifa world cup </h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
            </div>
        </div> 
    </div>
         
   {% endblock %}   
        
    

index/templates/index/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
    <div class="header">
        <div class="header-left">
             <img src="{% static 'images/ytlogo.png' %}">
        </div>
        <div class="header_search">
        
            <input type="text" class="ytsearch" placeholder="Search">
            <button class="search-btn" height="20px"><img src="{% static 'images/search.jpg' %}" width="20px"></button>
        </div>
        <div class="header-right">
            <img  class="imag" src="{% static 'images/video.png' %}">
            <img class="imag" src="{% static 'images/bell.jpg' %}">
            <img  class="imag" src="{% static 'images/account.png' %}">
        </div>
    </div> 
    <div class="content">
        <div class="sidebar">
            <div class="sidebarfield1">
                <a href="{% url 'index:index_home' %}"><img  class="imag2" src="{% static 'images/home.png' %}"></a>             <h4>Home</h4>
             
            </div>
             <div class="sidebarfield">
            <a href="{% url 'index:trending' %}"><img  class="imag2" src="{% static 'images/trending.png' %}"></a>
                <h4>Trending</h4>
        
             </div>
             <div class="sidebarfield">
            <a href="{% url 'index:subscription' %}"><img  class="imag2" src="{% static 'images/subscription.png' %}"></a>        
             <h4>Subscription</h4></div>
             <div class="sidebarfield">
                <hr >
             </div>
            <div class="sidebarfield">
                <a href="{% url 'index:library' %}"><img  class="imag2" src="{% static 'images/library.png' %}"></a>
                <h4>Library</h4>
            </div>
            <div class="sidebarfield">
               <a href="{% url 'index:history' %}"><img  class="imag2" src="{% static 'images/history.png' %}"></a>
                <h4>History</h4>
            </div>
            <div class="sidebarfield">
                    <a href=""><img  class="imag2" src="{% static 'images/videos.jpg' %}"></a>
                    <h4>Your videos</h4>
            </div>
            <div class="sidebarfield">
            <a href=""><img  class="imag2" src="{% static 'images/watch.png' %}"></a>                        
            <h4>Watch it later</h4>
            </div>
            <div class="sidebarfield">
                <a href=""><img  class="imag2" src="{% static 'images/like.png' %}"></a>                        
                <h4>Liked Videos</h4>
                </div>
        

        </div>
    </div>
    <!-- <div class ="buttonbar">
    <div class="button">
        <button value="All"></button>
        <button value="All"></button>
        <button value="All"></button>
        <button value="All"></button>
    </div> -->
 -->
        {% block content %}{% endblock %}
</div>
        

    
</body>
</html>

index/templates/index/subscription.html
{% extends 'index/master.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% block content %}
<div class="videos">
    <h2></h2>
    
    <div class="video_container">
        <div class="video">
            <img src="{% static 'images/trend1.jpg' %}">
            <div class="videoinfo">
            <h3>Xmas tree decoration</h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
        </div>
        </div>
        
        <div class="video">
            <img src="{% static 'images/trend2.jpg' %}">
            <div class="videoinfo">
            <h3>Xmas special</h3>
            <a href="">Lets Try This</a>
            <span>104K views</span>
            </div>
        </div>
        <div class="video">
            <img src="{% static 'images/trend3.jpg' %}">
            <div class="videoinfo">
            <h3> Xmas Candy</h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
            </div>
        </div>
        <div class="video">
            <img src="{% static 'images/trend4.jpg' %}">
            <div class="videoinfo">
            <h3>Xmas tree decor</h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
            </div>
        </div>
         <div class="video">
            <img src="{% static 'images/trend1.jpg' %}">
            <div class="videoinfo">
            <h3> Merry Xmas</h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
            </div>
        </div> 
         <div class="video">
            <img src="{% static 'images/trend6.jpg' %}">
            <div class="videoinfo">
            <h3>Tasty Candy </h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
            </div>
        </div> 
        <div class="video">
            <img src="{% static 'images/trend1.jpg' %}">
            <div class="videoinfo">
            <h3>Decor Xmas Tree</h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
            </div>
        </div>  
         <div class="video">
            <img src="{% static 'images/trend4.jpg' %}">
            <div class="videoinfo">
            <h3>Merry Xmas</h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
            </div>
        </div> 
        <div class="video">
            <img src="{% static 'images/trend2.jpg' %}">
            <div class="videoinfo">
            <h3> Wow Tasty Candy</h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
            </div>
        </div>  



    </div>
</div>
{% endblock %}

index/templates/index/trending.html
{% extends 'index/master.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% block content %}
<div class="videos">
    
    <h1>Trending Videos</h1>
    
    <div class="video_container">
        <div class="video">
            <img src="{% static 'images/sub1.jpg' %}">
            <div class="videoinfo">
            <h3>FIFA worldcup</h3>
            <a href="">Lets celebrate</a>
        </div>
        </div>
        
        <div class="video">
            <img src="{% static 'images/sub2.png' %}">
            <div class="videoinfo">
            <h3>fifa teams</h3>
            <span>104K views</span>
            </div>
        </div>
        <div class="video">
            <img src="{% static 'images/sub3.jpg' %}">
            <div class="videoinfo">
            <h3>fifa game chart</h3>
            <a href="">Lets celebrate</a>
            </div>
        </div>
        <div class="video">
            <img src="{% static 'images/sub4.jpg' %}">
            <div class="videoinfo">
            <h3>fifa group</h3>
            <a href="">lets enjoy</a>
            <span>10K views</span>
            </div>
        </div>
         <div class="video">
            <img src="{% static 'images/sub5.jpg' %}">
            <div class="videoinfo">
            <h3> fifa group chart</h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
            </div>
        </div> 
         <div class="video">
            <img src="{% static 'images/sub6.jpg' %}">
            <div class="videoinfo">
            <h3>fifa world cup </h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
            </div>
        </div> 
        <div class="video">
            <img src="{% static 'images/sub7.png' %}">
            <div class="videoinfo">
            <h3>fifa world cup</h3>
            <a href="">Lets celebrate</a>
            <span>10K views</span>
            </div>
        </div>  
         <div class="video">
            <img src="{% static 'images/sub2.png' %}">
            <div class="videoinfo">
            <h3>fifa world cup</h3>
            <a href="">Lets enjoy</a>
            <span>101K views</span>
            </div>
        </div> 
        <div class="video">
            <img src="{% static 'images/sub4.jpg' %}">
            <div class="videoinfo">
            <h3>fifa world cup</h3>
            <span>10K views</span>
            </div>
        </div>  
        
        <div class="video">
            <img src="{% static 'images/trend2.jpg' %}">
            <div class="videoinfo">
            <h3>Xmas special</h3>
            <a href="">Lets Try This</a>
            <span>104K views</span>
            </div>
        </div>
        <div class="video">
            <img src="{% static 'images/trend3.jpg' %}">
            <div class="videoinfo">
            <h3> Xmas Candy</h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
            </div>
        </div>
        <div class="video">
            <img src="{% static 'images/trend4.jpg' %}">
            <div class="videoinfo">
            <h3>Xmas tree decor</h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
            </div>
        </div>
         <div class="video">
            <img src="{% static 'images/trend1.jpg' %}">
            <div class="videoinfo">
            <h3> Merry Xmas</h3>
            <a href="">Lets Try This</a>
            <span>10K views</span>
            </div>
        </div> 



    </div>
</div>
{% endblock %}

ytclone/index/templates/index/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
    <div class="header">
        <div class="header-left">
             <img src="{% static 'images/ytlogo.png' %}">
        </div>
        <div class="header_search">
        
            <input type="text" class="ytsearch" placeholder="Search">
            <button class="search-btn" height="20px"><img src="{% static 'images/search.jpg' %}" width="20px"></button>
        </div>
        <div class="header-right">
            <img  class="imag" src="{% static 'images/video.png' %}">
            <img class="imag" src="{% static 'images/bell.jpg' %}">
            <img  class="imag" src="{% static 'images/account.png' %}">
        </div>
    </div> 
    <div class="content">
        <div class="sidebar">
            <div class="sidebarfield1">
                <a href="{% url 'index:index_home' %}"><img  class="imag2" src="{% static 'images/home.png' %}"></a>             <h4>Home</h4>
             
            </div>
             <div class="sidebarfield">
            <a href="{% url 'index:trending' %}"><img  class="imag2" src="{% static 'images/trending.png' %}"></a>
                <h4>Trending</h4>
        
             </div>
             <div class="sidebarfield">
            <a href="{% url 'index:subscription' %}"><img  class="imag2" src="{% static 'images/subscription.png' %}"></a>        
             <h4>Subscription</h4></div>
             <div class="sidebarfield">
                <hr >
             </div>
            <div class="sidebarfield">
                <a href=""><img  class="imag2" src="{% static 'images/library.png' %}"></a>
                <h4>Library</h4>
            </div>
            <div class="sidebarfield">
               <a href=""><img  class="imag2" src="{% static 'images/history.png' %}"></a>
                <h4>History</h4>
            </div>
            <div class="sidebarfield">
                    <a href=""><img  class="imag2" src="{% static 'images/videos.jpg' %}"></a>
                    <h4>Your videos</h4>
            </div>
            <div class="sidebarfield">
            <a href=""><img  class="imag2" src="{% static 'images/watch.png' %}"></a>                        
            <h4>Watch it later</h4>
            </div>
            <div class="sidebarfield">
                <a href=""><img  class="imag2" src="{% static 'images/like.png' %}"></a>                        
                <h4>Liked Videos</h4>
                </div>
        

        </div>
    </div>
    <!-- <div class ="buttonbar">
    <div class="button">
        <button value="All"></button>
        <button value="All"></button>
        <button value="All"></button>
        <button value="All"></button>
    </div> -->
 -->
        {% block content %}{% endblock %}
</div>
        

    
</body>
</html>